export enum TELE_BOX_MANAGER_EVENT {
    Focused = "focused",
    Blurred = "blurred",
    Created = "created",
    Removed = "removed",
    State = "state",
    AllBoxStatusInfo = "all_box_status_info",
    LastLastNotMinimizedBoxsStatus = "last_last_not_minimized_boxs_status",
    Move = "move",
    Resize = "resize",
    IntrinsicMove = "intrinsic_move",
    IntrinsicResize = "intrinsic_resize",
    VisualResize = "visual_resize",
    ZIndex = "z_index",
    PrefersColorScheme = "prefers_color_scheme",
    DarkMode = "dark_mode",
    // box标题栏操作
    BoxToMinimized = "boxToMinimized",
    BoxToMaximized = "boxToMaximized",
    BoxToNormal = "boxToNormal",
}
